<footer>
    <img src="images/logo3.png" class="logo" alt="TechCareers Logo">
    <ul>
        <li>Registered Office: <a href="https://www.google.com/maps">TechCareers Building</a></li>
        <li>Hotline: (+84) 832 244 3289</li>
        <li><a href="mailto:contact@techcareers.com">contact@techcareers.com</a></li>
        <li>Follow us on: <a href="https://www.facebook.com">TechCareers Inc.</a></li>
    </ul>
</footer>